### ISSUE TITLE
Invalid desktop file

### ISSUE THREAD

**Issue by probonopd** [oitsjustjose/Overleaf-Desktop#1]
`desktop-file-validate` says:

* error: value "public.app-category.productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "public.app-category.productivity"; values extending the format should start with "X-"
* hint: value "public.app-category.productivity;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu

References:
* https://standards.freedesktop.org/menu-spec/latest/apa.html
* https://github.com/AppImage/appimage.github.io/pull/1552

**Comment by oitsjustjose** [comment]
I'll look into fixing this in the next build -- clearly has something to do with [this line in `package.json`](https://github.com/oitsjustjose/Overleaf-Desktop/blob/master/package.json#L36)
