### ISSUE TITLE
Popout compiled view

### ISSUE THREAD

**Issue by Rich2020** [oitsjustjose/Overleaf-Desktop#3]
This is not an issue as it does not exist in the online version of Overleaf, so it is more a feature request but I was unable to locate a place to put this.

Having said that, it would be great if we could pop the compiled view (right-side of the UI) so that when using multiple monitors, the source can be on one screen while the compiled view can be on another.

**Comment by oitsjustjose** [comment]
Forgot to close this a bit ago -this has been implemented!!
