### ISSUE TITLE
Unable to start Overleaf on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by mumairanwar92** [oitsjustjose/Overleaf-Desktop#4]
I've installed overleaf latex using snap and overleaf is showing in application list but I'm to run overleaf. I click on the application but nothing happens. Tried using terminal too. Help is appreciated.

**Comment by oitsjustjose** [comment]
I'll test this as soon as I can -- I hope that the TypeScript rewrite would catch any previous errors that may have prevented you from using this app, but I'll test in a VM before releasing this new version!

**Comment by oitsjustjose** [comment]
Confirmed that the new build works in Ubuntu 18.04 and 20.04 via WSL.
