### ISSUE TITLE
Hide menu bar

### ISSUE THREAD

**Issue by DrRosental** [oitsjustjose/Overleaf-Desktop#6]
I'd like to hide the menu bar but it's not possible so far. Thanks for your work! [Regolith Linux 20.04 (Ubuntu)]

**Comment by DrRosental** [comment]
So, why is this closed?

![Screenshot from 2020-07-20 17-34-41](https://user-images.githubusercontent.com/56044852/87956670-9a989580-caaf-11ea-917c-91e3411c7f48.png)

**Comment by oitsjustjose** [comment]
Because I have _implemented_ - but not yet _released_ -  this feature. I have another job I need to work throughout the day today so I am unable to prepare the build process for the relatively huge update that is coming.

**Comment by DrRosental** [comment]
Thank you :)
